[pytest]
pythonpath = .

markers = 
    users: users endpoint tests
    auth: auth endpoint tests
    movies: movies endpoint tests
    theaters: theaters endpoint tests
    screens: screens endpoint tests
    shows: shows endpoint tests
    bookings: bookings endpoint tests
    