"""Initial schemas

Revision ID: 0778c0edff12
Revises: 134ddcd2dd47
Create Date: 2026-07-06 00:53:28.710478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0778c0edff12'
down_revision: Union[str, Sequence[str], None] = '134ddcd2dd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_seat_per_booking'), 'booking_seats', type_='unique')
    op.create_unique_constraint('unique_seat_per_show', 'booking_seats', ['show_id', 'seat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_seat_per_show', 'booking_seats', type_='unique')
    op.create_unique_constraint(op.f('unique_seat_per_booking'), 'booking_seats', ['show_id', 'seat_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
