"""Changed booking status pending to confirmed

Revision ID: d23faaa0ddbf
Revises: 72fea4f66b9b
Create Date: 2026-07-08 21:39:48.569168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23faaa0ddbf'
down_revision: Union[str, Sequence[str], None] = '72fea4f66b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
